### ISSUE TITLE
Add ability to read text activities

### ISSUE THREAD

**Issue by matt1484** [matt1484/bl3_auto_vip#10]
Need to add a way to get non-code related points

**Comment by squatto** [comment]
It’s a lot more involved, but you could use a headless browser for this. I put some time into an auto code redeemer a bit ago that was using [Laravel Dusk](https://laravel.com/docs/5.8/dusk) for the interaction. Another great option would be [Puppeteer](https://developers.google.com/web/tools/puppeteer/).

You could use the same strategy for the code redemption as well.

**Comment by matt1484** [comment]
I originally was using puppeteer

**Comment by matt1484** [comment]
However I can automate the reading of the text links since I think it’s just api calls based on what I’ve seen as well as the code

**Comment by squatto** [comment]
If all that they are looking for is to hit the URL for the text link, then you can definitely do it without a headless browser. I wonder if you could watch a YouTube video with the headless browser?

**Comment by matt1484** [comment]
I’m not sure. Only problem with a headless browser is that it adds a lot of dependencies, and it may not be feasible for iOS/Android. So far I haven’t needed a headless browser either, but we will see what challenges arise.

**Comment by squatto** [comment]
If you ended up going the headless browser route you’d either have to deal with dependencies or move everything to something like AWS Lambda. That’s a whole new game though, since you’d start incurring costs.

**Comment by matt1484** [comment]
Yeah. Trying to keep it free for the most part. As much as I love AWS

**Comment by squatto** [comment]
Can’t say that I blame you there! Hopefully it’s just as simple as hitting the URL and they aren’t relying on pixel trackers and correlating them with link clicks, or something convoluted like that.

**Comment by matt1484** [comment]
finished in v2.1
