### ISSUE TITLE
2.1 for Linux won't run

### ISSUE THREAD

**Issue by theDanielJLewis** [matt1484/bl3_auto_vip#19]
I don't know what's going on (I'm bringing this here from the Reddit thread), but I've narrowed it down to something with 2.1.

I have a VPS running Ubuntu 18.04. I can run 2.0 just fine, but 2.1, downloaded from either the zipped or non-zipped binary, will not run under Linux.

```
# ./bl3-auto-vip
-bash: ./bl3-auto-vip: No such file or directory
```

**Comment by theDanielJLewis** [comment]
I ran it from source using the Docker method and that seems to work, but I can't use the command-line switches to auto-enter my email and password.

**Comment by matt1484** [comment]
Seemed to work in docker, but to compile for Ubuntu you would have to install go 
https://tecadmin.net/install-go-on-ubuntu/ 
and then run 
`go get -u github.com/matt1484/bl3_auto_vip` 
then you would have to run 
`go run $GOPATH/github.com/matt1484/bl3_auto_vip/cmd/main.go`

**Comment by matt1484** [comment]
To run via docker with args should be as easy as `docker run -it bl3 go run cmd/main.go -e EMAIL -p PASSWORD`

**Comment by BradLugo** [comment]
@theDanielJLewis Are you sure you're in the directory that contains the binary? Bash should at least complain about file permissions rather than the file not being in that directory. You can double-check if the binary is in the current working directory with `ls`.

**Comment by theDanielJLewis** [comment]
@BradLugo, Yes, I'm in the directory and ran `chmod +x` on the file. _Exact same process_ for 2.0 and 2.1, but 2.1 Linux release won't run.

**Comment by theDanielJLewis** [comment]
I made a screencast to demonstrate the problem: https://www.dropbox.com/s/dlhc47zzmjxuf5a/bl3-auto%202.1%20linux%20problem.mp4?dl=0

**Comment by nega0** [comment]
The Linux bin is linked to a nonexistent dynamic loader. That's why you're getting the "file not found error". Additionally it's linked against musl-libc, instead of glibc.

```
~ nega@zinc
❯ file linux-bl3-auto-vip
linux-bl3-auto-vip: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, not stripped

~ nega@zinc
❯ ldd linux-bl3-auto-vip
	linux-vdso.so.1 (0x00007fff9899f000)
	libc.musl-x86_64.so.1 => not found
```

**Comment by BradLugo** [comment]
That's where I left off on my investigation. I'm wondering if this is due to compiling everything on Alpine and if there's a consistent way to compile these binaries so all distros have the loader, but I haven't gotten around to implementing a fix yet

**Comment by bmfrosty** [comment]
Probably appimage.
