### ISSUE TITLE
Support older VIP activities?

### ISSUE THREAD

**Issue by theDanielJLewis** [matt1484/bl3_auto_vip#20]
Now that you have it supporting _new_ VIP activities, could you consider making the script also run through _old_ activities?

**Comment by matt1484** [comment]
It does run through old ones. Or it should run through any you haven’t done.

**Comment by theDanielJLewis** [comment]
Maybe it simply skips any video activities.

**Comment by matt1484** [comment]
Yes it can’t do those. It seems that it makes you watch the video. Haven’t found a way around it
