### ISSUE TITLE
shift code souce

### ISSUE THREAD

**Issue by nega0** [matt1484/bl3_auto_vip#30]
https://shift.orcicorn.com might be a better source for shift codes than orcz.com

**Comment by matt1484** [comment]
That seems like that should work if it’s updated often

**Comment by test137E29B** [comment]
Orcicorn does seem to get updated fairly fast. ~30 Mins ago a shift code was released, and it's already on their site, but nothing since 21st October is on orcz

**Comment by matt1484** [comment]
Easy enough change. Probably won’t even require a new version

**Comment by Orcicorn** [comment]
Hiya!  Just now noticed this.

Matt I wanted to let you know that I also have .JSON feeds for codes the server believes to be active. If you don't want to parse through all the long RSS Feeds.

You can just rename any .XML Feed to .JSON and it'll be a trimmed list of ALL codes that were active when the server was last updated.  They're generated anytime I publish a new code.

For example: 
RSS for BL3 of all keys: https://shift.orcicorn.com/tags/borderlands3/index.xml
JSON for BL3 of non-expired keys; https://shift.orcicorn.com/tags/borderlands3/index.json

Give a shout (here/twitter/whatever) if I can be of any additional help

**Comment by squatto** [comment]
@Orcicorn this is killer, thank you! I was just sending you a tweet related to this in fact.

@matt1484 I'll tweak the script to pull from this source 👍

**Comment by Orcicorn** [comment]
Since my last comment I've actually documented the JSON Feeds.    It's pretty straight forward stuff.
https://shift.orcicorn.com/about/json/
