### ISSUE TITLE
Change VIP code source

### ISSUE THREAD

**Issue by squatto** [matt1484/bl3_auto_vip#37]
Just as I did in #36 for SHIFT codes, we should use [the JSON feed at shift.orcicorn.com](https://shift.orcicorn.com/vip-code/index.json) to pull active VIP codes. I can take care of it soon 👍

**Comment by MovieHQ** [comment]
Is there any way to get an windows EXE version of the change?

**Comment by Heaiser** [comment]
> Just as I did in #36 for SHIFT codes, we should use [the JSON feed at shift.orcicorn.com](https://shift.orcicorn.com/vip-code/index.json) to pull active VIP codes. I can take care of it soon 👍

Is this change coming soon?  Would really be excited about this one (despite the fact that no new VIP rewards have come out recently.
