### ISSUE TITLE
Shift code support

### ISSUE THREAD

**Issue by matt1484** [matt1484/bl3_auto_vip#9]
Add support for redeeming shift codes automatically

**Comment by squatto** [comment]
See my comment on #10: https://github.com/matt1484/bl3_auto_vip/issues/10#issuecomment-530661194

**Comment by matt1484** [comment]
Only problem that exists is how to store which codes have been redeemed, since borderlands doesn’t give me list of them for a given user, will likely just have to be a local file

**Comment by squatto** [comment]
That’s true. Maybe use SQLite?

**Comment by matt1484** [comment]
Yeah either that or a plain JSON or CSV file. It won’t be much data since I plan on having an external ordered list and just storing indexes of that list

**Comment by matt1484** [comment]
done in v2.1.0
